2019-12-23 15:54:38 [scrapy] DEBUG: Retrying <GET http://www.indeed.fr/robots.txt> (failed 1 times): DNS lookup failed: no results for hostname lookup: www.indeed.fr.
2019-12-23 15:54:38 [scrapy] DEBUG: Retrying <GET http://www.indeed.fr/robots.txt> (failed 2 times): DNS lookup failed: no results for hostname lookup: www.indeed.fr.
2019-12-23 15:54:38 [scrapy] DEBUG: Gave up retrying <GET http://www.indeed.fr/robots.txt> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.indeed.fr.
2019-12-23 15:54:38 [scrapy] ERROR: Error downloading <GET http://www.indeed.fr/robots.txt>: DNS lookup failed: no results for hostname lookup: www.indeed.fr.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py", line 982, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.indeed.fr.
2019-12-23 15:54:38 [scrapy] DEBUG: Retrying <GET http://www.indeed.fr/jobs?q=Informatique&l=Paris&sort=date&start=00> (failed 1 times): DNS lookup failed: no results for hostname lookup: www.indeed.fr.
2019-12-23 15:54:38 [scrapy] DEBUG: Retrying <GET http://www.indeed.fr/jobs?q=Informatique&l=Paris&sort=date&start=00> (failed 2 times): DNS lookup failed: no results for hostname lookup: www.indeed.fr.
2019-12-23 15:54:38 [scrapy] DEBUG: Gave up retrying <GET http://www.indeed.fr/jobs?q=Informatique&l=Paris&sort=date&start=00> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.indeed.fr.
2019-12-23 15:54:38 [scrapy] ERROR: Error downloading <GET http://www.indeed.fr/jobs?q=Informatique&l=Paris&sort=date&start=00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py", line 982, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.indeed.fr.
2019-12-23 15:54:38 [scrapy] DEBUG: Retrying <GET http://indeed.com/robots.txt> (failed 1 times): DNS lookup failed: no results for hostname lookup: indeed.com.
2019-12-23 15:54:38 [scrapy] DEBUG: Retrying <GET http://indeed.com/robots.txt> (failed 2 times): DNS lookup failed: no results for hostname lookup: indeed.com.
2019-12-23 15:54:38 [scrapy] DEBUG: Gave up retrying <GET http://indeed.com/robots.txt> (failed 3 times): DNS lookup failed: no results for hostname lookup: indeed.com.
2019-12-23 15:54:38 [scrapy] ERROR: Error downloading <GET http://indeed.com/robots.txt>: DNS lookup failed: no results for hostname lookup: indeed.com.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py", line 982, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: indeed.com.
2019-12-23 15:54:38 [scrapy] DEBUG: Retrying <GET http://indeed.com> (failed 1 times): DNS lookup failed: no results for hostname lookup: indeed.com.
2019-12-23 15:54:38 [scrapy] DEBUG: Retrying <GET http://indeed.com> (failed 2 times): DNS lookup failed: no results for hostname lookup: indeed.com.
2019-12-23 15:54:38 [scrapy] DEBUG: Gave up retrying <GET http://indeed.com> (failed 3 times): DNS lookup failed: no results for hostname lookup: indeed.com.
2019-12-23 15:54:38 [scrapy] ERROR: Error downloading <GET http://indeed.com>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/core/downloader/middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/endpoints.py", line 982, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: indeed.com.
2019-12-23 15:54:38 [scrapy] INFO: Closing spider (finished)
2019-12-23 15:54:38 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 12,
 'downloader/exception_type_count/twisted.internet.error.DNSLookupError': 12,
 'downloader/request_bytes': 2724,
 'downloader/request_count': 12,
 'downloader/request_method_count/GET': 12,
 'elapsed_time_seconds': 0.45609,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 12, 23, 14, 54, 38, 590276),
 'log_count/DEBUG': 12,
 'log_count/ERROR': 4,
 'log_count/INFO': 7,
 'memusage/max': 173404160,
 'memusage/startup': 173404160,
 'retry/count': 8,
 'retry/max_reached': 4,
 'retry/reason_count/twisted.internet.error.DNSLookupError': 8,
 "robotstxt/exception_count/<class 'twisted.internet.error.DNSLookupError'>": 2,
 'robotstxt/request_count': 2,
 'scheduler/dequeued': 6,
 'scheduler/dequeued/memory': 6,
 'scheduler/enqueued': 6,
 'scheduler/enqueued/memory': 6,
 'start_time': datetime.datetime(2019, 12, 23, 14, 54, 38, 134186)}
2019-12-23 15:54:38 [scrapy] INFO: Spider closed (finished)
